### ISSUE TITLE
tPostgresql postgis support needs a fix in the template "db_output_bulk.skeleton"

### ISSUE THREAD

**Issue by lucvanlinden** [talend-spatial/talend-spatial#82] opened 2020-04-25 08:00 UTC
Just for the info, not sure if it is better to use the postgis component from Talend SDI or not we tested the postgresql dboutput component as it has support for spatial.

However there is a "bug" in it that is uses the wrong function while producing teh insert statements.

the template file: db_output_bulk.skeleton

under: 

plugins\org.talend.designer.components.localprovider_7.1.1.20181026_1147\components\templates

contains follwing piece of code which is "iported into the relevant (postgresql) output_begin.javajet

public String getSqlStmt() {
            if(this.getColumn()!=null) {
                if (this.getColumn().getTalendType().equals("id_Geometry")) {
                    
                    if ("MDSYS.SDO_GEOMETRY".equalsIgnoreCase(this.getColumn().getType())) {
                        return "?";
                    } else {
                        return "GeomFromText(?, ?)";    // For PostGIS
                    }
                } else {
                    return this.sqlStmt;
                }
            } else {
                return this.sqlStmt;
            }
        }

The line

return "GeomFromText(?, ?)";    // For PostGIS

needs to become

return "ST_GeomFromText(?, ?)";    // For PostGIS

as the function GeomFromText as such does not exist in Postgis and will return a posgres error.

**Comment by fxprunayre** [comment] 2020-04-27 09:06
Added on Talend side https://jira.talendforge.org/browse/TDI-44129. Thanks

**Comment by fxprunayre** [comment] 2020-05-05 08:07
Duplicate of https://github.com/talend-spatial/talend-spatial/issues/68

**Closed as completed by fxprunayre** 2020-05-05 08:07 UTC
